---
title: "Manpower Utilization Survey"
author: "Hsuwei"
date: "2018/4/13"
output: html_document
---

```{r, message=FALSE, warning=FALSE, include=FALSE}

load("/Users/hsuwei/Desktop/manpower/result/manpower.RData")
library(tidyverse)
library(magrittr)
library(gridExtra)
library(ggthemes)

```

```{r}
knitr::kable(alldf.en)
```


```{r, echo=FALSE, warning=FALSE}
## age specific
alldf.en %>%
  select(1:5) %>%
  gather("type", "income", -year) %>%
  mutate_at(c("year", "income"), as.numeric) %>%
ggplot(data = ., mapping = aes(x = year, y = income, color = type)) +
  geom_line(size=1) + theme_solarized() + scale_colour_solarized("blue") +
  ggtitle("Age-Specific Income")
  
```

```{r, echo=FALSE}
## industry specific
alldf.en %>%
  select(1, 6:8) %>%
  gather("type", "income", -year) %>%
  mutate_at(c("year", "income"), as.numeric) %>%
  ggplot(data = ., mapping = aes(x = year, y = income, color = type)) + 
  geom_line(size = 1) + 
  theme_solarized() + scale_colour_solarized("blue") +
  ggtitle("Industry-specific Income")

```

```{r, echo=FALSE}
## worktype specific
par(mfrow=c(1,3))

alldf.en %>%
  select(1, 9:10) %>%
  gather("type", "income", -year) %>%
  mutate_at(c("year", "income"), as.numeric) %>%
  ggplot(data = ., mapping = aes(x = year, y = income, color = type)) + 
  geom_line(size = 1) + 
  theme_solarized() + scale_colour_solarized("blue") +
  ggtitle("Worktype-Specific Income1")


alldf.en %>%
  select(1, 11:12) %>%
  gather("type", "income", -year) %>%
  mutate_at(c("year", "income"), as.numeric) %>%
  ggplot(data = ., mapping = aes(x = year, y = income, color = type)) + 
  geom_line(size = 1) + 
  theme_solarized() + scale_colour_solarized("blue") +
  ggtitle("Worktype-Specific Income2")

alldf.en %>%
  select(1, 13:14) %>%
  gather("type", "income", -year) %>%
  mutate_at(c("year", "income"), as.numeric) %>%
  ggplot(data = ., mapping = aes(x = year, y = income, color = type)) + 
  geom_line(size = 1) + 
  theme_solarized() + scale_colour_solarized("blue") +
  ggtitle("Worktype-Specific Income3")

```

